### ISSUE TITLE
0.5.3 Telegram Notification Issue

### ISSUE THREAD

**Issue by forewerkisser** [NightStrang6r/FunPayServer#14]
В телеграм не приходят уведомления о новых сообщениях на фп, никакие
В конфиге включено, бот активен, проблема только с этим
Допускаю что я мог допустить ошибку в конфиге поэтому вот

# Автоответ. [1 - включить, 0 - выключить]
autoResponse: 0

# Приветственное сообщение для новых покупателей. [1 - включить, 0 - выключить]
greetingMessage: 0

[Telegram]
# Настройки Telegram бота

# Включить бота. [1 - включить, 0 - выключить]
enabled: 1

# Уведомления о новом сообщении. [1 - включить, 0 - выключить]
newMessageNotification: 1

# Уведомления о новом заказе. [1 - включить, 0 - выключить]
newOrderNotification: 1

# Уведомления о поднятии лотов. [1 - включить, 0 - выключить]
lotsRaiseNotification: 1

# Уведомления о выдаче товара. [1 - включить, 0 - выключить]
deliveryNotification: 1

**Comment by NightStrang6r** [comment]
Это баг. Поставь greetingMessage: 1, а greetingMessageText: (тут оставь пустым)
