### ISSUE TITLE
Бот не может подключиться к интернету, хоть интернет и есть

### ISSUE THREAD

**Issue by ZeInSoRiTy** [NightStrang6r/FunPayServer#17]
Скрин
![image](https://github.com/NightStrang6r/FunPayServer/assets/101979081/dc31c0f5-246e-45be-80a0-4ca221eddbd6)
Пользовался 4 месяца почти, всё было хорошо, сейчас вот это

**Comment by NightStrang6r** [comment]
Бот не запустится на новой версии NodeJS 20. Используйте NodeJS 16.x.x
