### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by kenuna** [NightStrang6r/FunPayServer#20]
> [11.08.2023] [01:34:23]: Ошибка: необработанное исключение. Сообщите об этом разработчику.
> [11.08.2023] [01:34:23]: FetchError: request to https://api.telegram.org/bot62718****:[REDACTED]/getMe failed, reason: connect ENOBUFS 149.154.167.220:443 - Local (undefined:undefined)
    at ClientRequest.<anonymous> (C:\Users\Administrator\Desktop\kenuna\node_modules\telegraf\node_modules\node-fetch\lib\index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> [11.08.2023] [01:34:23]: Ошибка при запросе (нет доступа к интернету / funpay): FetchError: request to https://funpay.com/lots/raise failed, reason: connect ENOBUFS 188.114.99.224:443 - Local (undefined:undefined)
> [11.08.2023] [01:34:23]: Ошибка при поднятии предложений: TypeError: Cannot read properties of undefined (reading 'json')
> [11.08.2023] [01:34:23]: Не удалось поднять предложение Услуги Discord: undefined
> [11.08.2023] [01:34:23]: Ошибка при запросе (нет доступа к интернету / funpay): FetchError: request to https://funpay.com/lots/raise failed, reason: connect ENOBUFS 188.114.99.224:443 - Local (undefined:undefined)
> [11.08.2023] [01:34:23]: Ошибка при поднятии предложений: TypeError: Cannot read properties of undefined (reading 'json')
> [11.08.2023] [01:34:23]: Не удалось поднять предложение Аккаунты Forza Horizon: undefined
> [11.08.2023] [01:34:23]: Ошибка при запросе (нет доступа к интернету / funpay): FetchError: request to https://funpay.com/lots/raise failed, reason: connect ENOBUFS 188.114.99.224:443 - Local (undefined:undefined)
> [11.08.2023] [01:34:23]: Ошибка при поднятии предложений: TypeError: Cannot read properties of undefined (reading 'json')
> [11.08.2023] [01:34:23]: Не удалось поднять предложение Прочее Minecraft: undefined
> [11.08.2023] [01:34:23]: Ошибка при запросе (нет доступа к интернету / funpay): FetchError: request to https://funpay.com/lots/raise failed, reason: connect ENOBUFS 188.114.99.224:443 - Local (undefined:undefined)
> [11.08.2023] [01:34:23]: Ошибка при поднятии предложений: TypeError: Cannot read properties of undefined (reading 'json')
> [11.08.2023] [01:34:23]: Не удалось поднять предложение Услуги Minecraft: undefined
> [11.08.2023] [01:34:23]: Ошибка при запросе (нет доступа к интернету / funpay): FetchError: request to https://funpay.com/lots/raise failed, reason: connect ENOBUFS 188.114.99.224:443 - Local (undefined:undefined)
> [11.08.2023] [01:34:23]: Ошибка при поднятии предложений: TypeError: Cannot read properties of undefined (reading 'json')
> [11.08.2023] [01:34:23]: Не удалось поднять предложение Аккаунты Xbox: undefined
> [11.08.2023] [01:34:23]: Автовыдача запущена, загружено 5 товара(ов).

**Comment by NightStrang6r** [comment]
Выглядит как буд-то нет доступа к интернету, так как не проходят запросы не на Telegram, не на FunPay.
