### ISSUE TITLE
Не проверяет наличие заказов

### ISSUE THREAD

**Issue by xotabb** [NightStrang6r/FunPayServer#24]
Если запускаю бота и при этом имеются заказы он их не проверяет, и не работает автовыдача. Работает проверка заказов только если заказ был оформлен после того как был запущен бот. Эта система так и должна работать или это баг?

Мой файл settings

[FunPay]
# Настройки FunPay бота

# Ключ авторизации в FunPay.
# Получите его с помощью расширения Edit This Cookie для браузера.
golden_key: 

# Всегда онлайн. [1 - включить, 0 - выключить]
alwaysOnline: 1

# Автоподнятие лотов. [1 - включить, 0 - выключить]
lotsRaise: 1

# Автоактивация лотов после продажи. [1 - включить, 0 - выключить]
goodsStateCheck: 0

# Автовыдача товаров. [1 - включить, 0 - выключить]
autoDelivery: 1

# Автоответ. [1 - включить, 0 - выключить]
autoResponse: 0

# Приветственное сообщение для новых покупателей. [1 - включить, 0 - выключить]
greetingMessage: 0

# Текст приветственного сообщения для новых покупателей. 
# Для переноса строки в сообщении используйте \n.
# Доступные переменные: {name} - имя покупателя.
greetingMessageText: Привет, {name}!\nПродавец скоро ответит на твоё сообщение.

# Команда для проверки работы автовыдачи. [1 - включить, 0 - выключить]
autoDeliveryTestCommand: 0

# Текст, который отправляется в самом начале каждого сообщения бота в чате.
# Оставьте поле пустым, если не хотите использовать эту функцию.
waterMark: 

[Telegram]
# Настройки Telegram бота

# Включить бота. [1 - включить, 0 - выключить]
enabled: 0

# Токен бота. Получить его можно у @BotFather
token: 

# Ник (логин) администратора в Telegram без @. Нужен для авторизации в боте.
userName: MyTelegramLogin

# Уведомления о новом сообщении. [1 - включить, 0 - выключить]
newMessageNotification: 0

# Уведомления о новом заказе. [1 - включить, 0 - выключить]
newOrderNotification: 0

# Уведомления о поднятии лотов. [1 - включить, 0 - выключить]
lotsRaiseNotification: 0

# Уведомления о выдаче товара. [1 - включить, 0 - выключить]
deliveryNotification: 0

[Proxy]
# Настройки прокси

# Включить прокси. [1 - включить, 0 - выключить]
enabled: 0

# Хост прокси
host: 

# Порт прокси
port:

# Логин прокси (если есть)
login: 

# Пароль прокси (если есть)
pass: 

# Тип прокси. [http]
type: http

**Comment by NightStrang6r** [comment]
Да, эта система так и должна работать. Так как если бы он выдавал и на заказы, которые были раньше, было бы непонятно кому товар был уже выдан, а кому - нет. Ведь бот не был запущен раньше и он не знает был ли выдан товар вручную. Т.е. это помогает избежать проблемы с повторной выдачей товара.
