### ISSUE TITLE
всегда онлайн работает даже если выключен

### ISSUE THREAD

**Issue by pushkinb** [NightStrang6r/FunPayServer#29]
Привет, в настройках я выключил функцию вечного онлайна, но как оказалось она все равно работает, вернее какие-то другие функции заставляют сайт думать что ты онлайн, из-за чего мне идут заказы даже когда я сплю и т.д.
можете пожалуйста помочь как мне убрать вечный онлайн?

**Comment by NightStrang6r** [comment]
Привет. Это невозможно убрать. При любом запросе бота FunPay будет отмечать, что аккаунт в онлайне. Функция вечного онлайна нужна, если пользователь точно хочет чтобы аккаунт был всегда в онлайне, независимо от других функций бота.
